config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    # get "sign_in", :to => "users/sessions#new"     #test用
    # get "sign_out", :to => "users/sessions#destroy"   #test用
  end

  root to: 'homes#top'
  get 'homes/about'

  resources :contacts, only: [:new, :create]

  resources :blogs do
    collection do
      get 'search'
      get "sort"
    end
    resources :blog_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
  end
  put "/users/:id/withdrawal" => "users#withdrawal", as: 'users_withdrawal' # 退会機能

  resources :genres, only: [:index, :create, :edit, :update, :destroy]

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  attachment :image # destroy: false
  attachment :profile_image, destroy: false

  belongs_to :genre

  belongs_to :user

  has_many:blog_comments, dependent: :destroy
  has_many:favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.ranking
    Blog.select('blogs.*', 'count(favorites.id) AS favorites').
      left_joins(:favorites).
      group('blogs.id').
      order('favorites DESC').
      limit(5)
  end
end

app/models/blog_comment.rb
class BlogComment < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :blogs, dependent: :destroy
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  attachment :image, destroy: false

  is_impressionable # トラッキング

  has_many :blogs, dependent: :destroy
  has_many :blog_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # name を入力必須としているならば， user.name = "ゲスト" などが追加で必要
    end
  end

  def active_for_authentication?
    super && (is_valid == true)
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_q, only: [:index, :search]

  def index
    @blogs = @q.result.page(params[:page]).reverse_order
    @blogs_new = Blog.all.order(created_at: "DESC").limit(5)
    @blogs_ranking = Blog.ranking
  end

  def new
    @blog = Blog.new
    @genres = Genre.all
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user = current_user
    @blog.save
    redirect_to blogs_path
  end

  def show
    @blogs = Blog.all
    @blog = Blog.find(params[:id])
    @blog_comment = BlogComment.new
  end

  def edit
    @blog = Blog.find(params[:id])
    @genres = Genre.all
  end

  def update
    @blog = Blog.find(params[:id])
    @blog.update(blog_params)
    redirect_to blog_path(@blog)
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end

  def search
    @results = @q.result.page(params[:page]).reverse_order
  end

  def sort # sort機能　params受け取り
    @params = params[:scene]
    @blogs = Blog.where(scene: @params)
  end

  private

  def blog_params
    params.require(:blog).permit(:image, :scene, :partner, :name, :price, :title, :body, :genre_id)
  end

  def set_q
    @q = Blog.ransack(params[:q])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      redirect_to new_contact_path, notice: '※メッセージが送信されました'

    else
      redirect_to new_contact_path
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :message)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @blog = Blog.find(params[:blog_id])
    favorite = current_user.favorites.new(blog_id: @blog.id)
    favorite.save
    # redirect_to request.referer
  end

  def destroy
    @blog = Blog.find(params[:blog_id])
    favorite = current_user.favorites.find_by(blog_id: @blog.id)
    favorite.destroy
    # redirect_to request.referer
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to genres_path
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to genres_path(@genre)
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @blogs_new = Blog.all.order(created_at: "DESC").limit(10)
    @blogs_ranking = Blog.select('blogs.*', 'count(favorites.id) AS favorites').
      left_joins(:favorites).
      group('blogs.id').
      order('favorites DESC').
      limit(5)
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_q, only: [:index, :search]
  impressionist :actions => [:show]

  def index
    @users = @q.result.page(params[:page]).reverse_order
  end

  def show
    @user = User.find(params[:id])
    impressionist(@user) # トラッキング
    @users = User.all
    @blogs = @user.blogs.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(params_user)
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
  end

  def search
    @results = @q.result.page(params[:page]).reverse_order
  end

  def withdrawal
    @user = User.find(params[:id])
    @user.update(is_valid: false) # is_validカラムにフラグを立てる(defaultはtrue)
    reset_session # ログアウトさせる
    flash[:notice] = "退会完了致しました。"
    redirect_to root_path
  end

  private

  def set_q
    @q = User.ransack(params[:q])
  end

  def params_user
    params.require(:user).permit(:profile_image, :name, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_comments_helper.rb
module BlogCommentsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<div class="col-5">

  <%=form_with model: blog, local:true do |f| %>
  <h4>画像</h4>
  <%= f.attachment_field :image %>
  <h4 class="mt-2">場面</h4>
  <%= f.select :scene, {'誕生日': "誕生日",'記念日': "記念日",'お祝い': "お祝い",'サプライズ': "サプライズ",'自分へのご褒美': "自分へのご褒美",'プロポーズ': "プロポーズ",'クリスマス': "クリスマス",'その他': "その他"}, { include_blank: '選択してください'}, { class: 'form-control' , required: true, } %>
  <h4 class="mt-2">相手</h4>
  <%= f.select :partner, {'家族・親戚': "家族・親戚",'彼氏・彼女': "彼氏・彼女",'友達・知人': "友達・知人",'ビジネス・目上の人': "ビジネス・目上の人",'その他': "その他"}, { include_blank: '選択してください'}, { class: 'form-control' , required: true, } %>
  <h4 class="mt-2">ジャンル</h4>
  <%= f.collection_select(:genre_id, @genres, :id, :name )%>
  <h4 class="mt-2">製品名</h4>
  <%=f.text_field :name, size: "44x13" %>
  <h4 class="mt-2">価格</h4>
  <%= f.select :price, {'¥1,000': "¥1,000",'¥2,000': "¥2,000",'¥3,000': "¥3,000",'¥4,000': "¥4,000",'¥5,000': "¥5,000",'¥10,000': "¥10,000",'¥50,000': "¥50,000",'その他': "その他"}, { include_blank: '選択してください'}, { class: 'form-control' , required: true, } %>

  <h4>タイトル</h4>
  <%=f.text_field :title %>
  <h4 class="mt-2">内容</h4>
  <%=f.text_area :body, size: "60x13" %><br>

  <%=f.submit "post" %>
  <% end %>

</div>

app/views/blogs/_index.html.erb
 <div class="row mt-5 ml-5">
   <% blogs.each do |blog| %>
    <div id="blog_<%= blog.id %>">

  <div class="col-auto">
   <p><%= link_to blog_path(blog) do %>
       <%=attachment_image_tag blog, :image, :fill, 180, 140, format: 'jpeg', fallback: "no_image.png", size:'180x140' %>
       <% end %></p>

  <div class="d-flex justify-content-between">
   <div>
     <%=blog.name %><br>
     <%=blog.genre.name %><br>
     <%=blog.price %></p>
   </div>
   <div>
     <div class="favorite-btn"><%= render "favorites/favorite-btn", blog: blog %></div>
    </div>
   </div>
  </div>

   </div>
   <% end %>
  </div>

app/views/blogs/_scene.html.erb
 <div class ="mt-5 mr-5">

  <h4 class = "border-bottom border-dark fas fa-search-plus">シーン検索</h4>

  <div class="mt-3"><%=link_to sort_blogs_path(scene: "誕生日") do %>
                     <%= image_tag "birthday3.jpg",width:"150",height:"150" %>
                    <% end %>
  </div>

  <div class="mt-3"><%=link_to  sort_blogs_path(scene: "記念日") do %>
                     <%= image_tag "hands.jpg",width:"150",height:"150" %>
                    <% end %>
  </div>

  <div class="mt-3"><%=link_to sort_blogs_path(scene: "お祝い") do %>
                     <%= image_tag "new-years.jpg",width:"150",height:"150" %>
                    <% end %>
  </div>

  <div class="mt-3"><%=link_to sort_blogs_path(scene: "サプライズ") do %>
                     <%= image_tag "bouquet.jpg",width:"150",height:"150" %>
                    <% end %>
  </div>

  <div class="mt-3"><%=link_to sort_blogs_path(scene: "自分へのご褒美") do %>
                     <%= image_tag "woman.jpg",width:"150",height:"150" %>
                    <% end %>
  </div>

  <div class="mt-3"><%=link_to sort_blogs_path(scene: "プロポーズ") do %>
                     <%= image_tag "sunset.jpg",width:"150",height:"150" %>
                    <% end %>
  </div>

  <div class="mt-3"><%=link_to sort_blogs_path(scene: "クリスマス") do %>
                     <%= image_tag "moon.jpg",width:"150",height:"150" %>
                    <% end %>
  </div>

  <div class="mt-3"><%=link_to sort_blogs_path(scene: "その他") do %>
                     <%= image_tag "gift-2.jpg",width:"150",height:"150" %>
                    <% end %>
  </div>

 </div>

app/views/blogs/edit.html.erb
<div class ="containar-fluid">
 <div class ="row mt-5 ml-5">

  <h1 class ="mb-3">投稿編集</h1>

   <div class="col-lg-12">

 <%= render "form",blog: @blog %>

  </div>
 </div>
</div>

app/views/blogs/index.html.erb
<main>

 <div class="containar-fluid">
  <div class="d-flex justify-content-between">
   <div class ="mt-5 ml-5">
    <h1><% if current_user.name == User.find_by(name: "ゲスト").name %>
         <h6>★ゲストログインの為、投稿機能は使用できません</h6>
        <% else %>
         <h2><%=link_to "新規投稿", new_blog_path, class: "fas fa-clone text-dark"  %></h2>
        <% end %>
    </h1>

   </div>

   <div class ="mt-4 mr-5">
     <%= search_form_for @q, url: search_blogs_path do |f| %>
     <%#= f.label :scene_or_partner_or_name_or_price_or_title_cont, '検索' %>
     <%= f.search_field :scene_or_partner_or_name_or_price_or_title_cont %>
     <%= f.submit '検索' %>
     <% end %>

     <h4 class="flex fas fa-search-plus mt-3">投稿一覧 並び替え</h4>
     <ul>
      <li class="list-inline-item"><%= sort_link(@q, :scene, "場面順") %></li>
      <li class="list-inline-item"><%= sort_link(@q, :partner, "相手順") %></li>
    　<li class="list-inline-item"><%= sort_link(@q, :genre_name, "ジャンル順") %></li>
    　<li class="list-inline-item"><%= sort_link(@q, :name, "製品名順") %></li>
    　<li class="list-inline-item"><%= sort_link(@q, :price, "価格順") %></li>
     </ul>
   </div>
  </div>

  <div class ="fx-container mt-2 ml-5"><!-- sort機能　params受け渡し -->
   <div><%=link_to sort_blogs_path(scene: "誕生日") do %>
        <%= image_tag "birthday3.jpg",width:"45%",height:"250" %>
       <% end %>

       <%=link_to  sort_blogs_path(scene: "記念日") do %>
        <%= image_tag "hands.jpg",width:"45%",height:"250" %>
       <% end %>
   </div>
  </div>

  <div class="d-flex">
   <div>


  <div class ="mt-5 ml-5">
　 <h1 class = "border-bottom border-dark fas fa-crown"> 人気ランキング</h1>
  </div>

  <div class="row mt-3 ml-5">
   <% @blogs_ranking.each.with_index(1) do |blog, i| %>
   <div id="blog_<%= blog.id %>">
  <div class="col-auto <%#border border-dark rounded%>">

   <div class ="text-center">
    <P class="fas fa-crown text-warning"> 第<%= i %>位</P>
   </div>

   <p><%= link_to blog_path(blog) do %>
       <%=attachment_image_tag blog, :image, :fill, 180, 140, format: 'jpeg', fallback: "no_image.png", size:'180x140' %>
       <% end %></p>

  <div class="d-flex justify-content-between">
   <div>
     <%=blog.name %><br>
     <%=blog.genre.name %><br>
     <%=blog.price %>
   </div>
   <div>
    <div class="favorite-btn"><%= render "favorites/favorite-btn", blog: blog %></div>
   </div>
  </div>
 </div>

   </div>
   <% end %>
  </div>


  <div class ="mt-5 ml-5">
　 <h1 class = "border-bottom border-dark fas fa-calendar-day"> 新着投稿</h1>
　</div>

  <div class="row mt-3 ml-5">
   <% @blogs_new.each do |blog| %>
    <div id="blog_<%= blog.id %>">
  <div class="col-auto">
   <p><%= link_to blog_path(blog) do %>
       <%=attachment_image_tag blog, :image, :fill, 180, 140, format: 'jpeg', fallback: "no_image.png", size:'180x140' %>
       <% end %></p>

  <div class="d-flex justify-content-between">
   <div>
     <%=blog.name %><br>
     <%=blog.genre.name %><br>
     <%=blog.price %>
   </div>
   <div>
    <div class="favorite-btn"><%= render "favorites/favorite-btn", blog: blog %></div>
   </div>
  </div>
 </div>

   </div>
   <% end %>
  </div>



  <div class ="mt-5 ml-5"><%# sort機能　params受け渡し %>
   <h6><%=link_to sort_blogs_path(scene: "お祝い") do %>
                     <%= image_tag "new-years.jpg",width:"45%",height:"250" %>
                    <% end %>

       <%=link_to sort_blogs_path(scene: "サプライズ") do %>
                     <%= image_tag "bouquet.jpg",width:"45%",height:"250" %>
                    <% end %>
   </h6>
  </div>


  <div class ="mt-5 ml-5">
　 <h1 class = "border-bottom border-dark fas fa-list"> 投稿一覧</h1>
　</div>

   <%= render "index" , blogs: @blogs %>
   <div class ="mt-1 ml-5 mr-5">
    <%= paginate @blogs %></div>


  <div class ="mt-5 ml-5"><%# sort機能　params受け渡し %>
   <h6><%=link_to sort_blogs_path(scene: "自分へのご褒美") do %>
                     <%= image_tag "woman.jpg",width:"45%",height:"250" %>
                    <% end %>

       <%=link_to sort_blogs_path(scene: "プロポーズ") do %>
                     <%= image_tag "sunset.jpg",width:"45%",height:"250" %>
                    <% end %>
   </h6>
  </div>

 </div>

 <%= render "scene" %>

 </div>
</main>

app/views/blogs/new.html.erb
<div class ="containar-fluid">
 <h1 class="mt-5 ml-5">新規投稿</h1>

 <div class ="row mt-3 ml-5">


 <%= render "form",blog: @blog %>

 </div>
</div>

app/views/blogs/search.html.erb
<h1 class="mt-5 ml-5 border-bottom border-dark fas fa-search-plus">検索結果</h1>

 <div class="row mt-3 ml-5">
  <% @results.each do |blog| %>
   <div class="col-auto">
   <p><%= link_to blog_path(blog) do %>
       <%=attachment_image_tag blog, :image, :fill, 180, 140, format: 'jpeg' %>
       <% end %></p>

  <div class="row">
   <div class="col-8">
     <%=blog.name %><br>
     <%=blog.genre.name %><br>
     <%=blog.price %></p>
   </div>
   <div class="col-4">
    <p><% if blog.favorited_by?(current_user) %>
        <%= link_to blog_favorites_path(blog), method: :delete do %>
         ♥<%= blog.favorites.count %>
        <% end %>
       <% else %>
        <%= link_to blog_favorites_path(blog), method: :post do %>
         ♡<%= blog.favorites.count %>
        <% end %>
       <% end %>
     </p>
    </div>
   </div>

   </div>
   <% end %>
  </div>
 <%= paginate @results %>

app/views/blogs/show.html.erb
<main>
 <div class="containar-fluid">
  <div class="row">
   <div class ="col-lg-5 mt-5 ml-5 mr-3">
    <p4><%=attachment_image_tag @blog, :image, :fill, 480, 360, format: 'jpeg', fallback: "no_image.png", size:'480x360' %></p4>
   </div>
   <div class ="col-lg-5 mt-5 ml-5 mr-5">
    <h2 class ="fas fa-calendar-day"> <%= @blog.created_at.strftime('%Y/%m/%d') %></h2>
    <h2><%=@blog.scene %></h2>
    <h2><%=@blog.partner %></h2>
    <h2><%=@blog.genre.name %></h2>
    <h2><%=@blog.name %></h2>
    <h2><%=@blog.price %></h2>
    <h2>♥<%=@blog.favorites.count %></h2>

    <h4><% if @blog.user == current_user %>
        <%= link_to "編集", edit_blog_path(@blog) %>
        <%= link_to "削除", blog_path(@blog), method: :delete%>
        <% end %>
    </h4>
   </div>
  </div>

  <div class ="mt-5 ml-5">
  <h2><%=attachment_image_tag @blog.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.png", size:'180x140' %>
      <%=@blog.user.name %>
  </h2>
  <h2 class="mt-5"><%=@blog.title %></h2>
  <p class="mt-3"><%=@blog.body %></p>
  </div>

  <div class="comments mt-5 ml-5">
   <h6>コメント件数：<%= @blog.blog_comments.count %></h6>
     <% @blog.blog_comments.each do |blog_comment| %>
     <h8>
     <%= blog_comment.created_at.strftime('%Y/%m/%d') %> <%= blog_comment.user.name %> <%= blog_comment.comment %>
     <% if blog_comment.user == current_user %>
     </h8>
     <div class="comment-delete">
      <%= link_to "削除", blog_blog_comment_path(blog_comment.blog, blog_comment), method: :delete %>
     </div>
    <% end %>
    <% end %>
   </div>

   <div class="new-comment mt-2 ml-5">
    <%= form_with(model:[@blog, @blog_comment], local: true) do |f| %>
    <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
    <% end %>
   </div>

  <%= render "index" , blogs: @blogs %>
 </div>
</main>

app/views/blogs/sort.html.erb
<main>

 <div class="containar-fluid">
  <div class="row mt-5 ml-5">

   <h1 class=" border-bottom border-dark fas fa-list"> <%= @params %></h1>

   <%= render "index" , blogs: @blogs %>

app/views/contacts/new.html.erb
<div class ="containar-fluid mt-5 ml-5">

 <h1>PF お問い合わせフォーム</h1><br>

<p>この度は、お忙しい中、for you をご覧頂き、誠に有難う御座います。<br>
皆様より頂きましたアドバイス、ご指摘を元に今後の学習やPF改善に取り組んでいきたいと思っておりますので、<br>
ご意見、ご感想等御座いましたら、是非メッセージを頂けますと幸いです。</p>

<%= form_with model: @contact do |f| %>
   <h5>名前(ニックネーム)</h5>
   <%= f.text_field :name %><br>
   <h5>ご意見・ご感想</h5>
   <%= f.text_area :message, size: "60x5" %><br>
   <%= f.submit "メッセージを送信" %>
<% end %>

　<h6 class ="text-danger"><%= flash[:notice] %></h6>

</div>

app/views/favorites/_favorite-btn.html.erb
<% if blog.favorited_by?(current_user) %>
 <%= link_to blog_favorites_path(blog), method: :delete, remote: true do %>
  ♥<%= blog.favorites.count %>
   <% end %>
<% else %>
 <%= link_to blog_favorites_path(blog), method: :post, remote: true do %>
   ♡<%= blog.favorites.count %>
 <% end %>
<% end %>

app/views/favorites/create.js.erb
$("#blog_<%= @blog.id %> .favorite-btn").html("<%= j(render 'favorites/favorite-btn', blog: @blog) %>");

app/views/favorites/destroy.js.erb
$("#blog_<%= @blog.id %> .favorite-btn").html("<%= j(render 'favorites/favorite-btn', blog: @blog) %>");

app/views/genres/edit.html.erb
<div class ="mt-5 ml-5">

 <h1>ジャンル編集</h1>

   <%= form_with model: @genre, local:true do |f| %>
   <%=f.text_field :name %>
   <%=f.submit "Update" %>
   <% end %>

</div>

app/views/genres/index.html.erb
<div class ="mt-5 ml-5">
 <h1>ジャンル一覧</h1>

   <%=form_with model: @genre, local:true do |f| %>
   <%=f.text_field :name %>
   <%=f.submit "追加" %>
   <% end %>

  <div class ="mt-3">
   <% @genres.each do |genre| %>
    <h6><%= genre.name %>
       <%=link_to "編集", edit_genre_path(genre) %>
       <%=link_to "削除", genre_path(genre), method: :delete %>
    </h6>
   <% end %>
  </div>

 </div>