config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    # get "sign_in", :to => "users/sessions#new"     #test用
    # get "sign_out", :to => "users/sessions#destroy"   #test用
  end

  root to: 'homes#top'
  get 'homes/about'

  resources :contacts, only: [:new, :create]

  resources :blogs do
    collection do
      get 'search'
      get "sort"
    end
    resources :blog_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
  end
  put "/users/:id/withdrawal" => "users#withdrawal", as: 'users_withdrawal' # 退会機能

  resources :genres, only: [:index, :create, :edit, :update, :destroy]

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  attachment :image, destroy: false

  is_impressionable # トラッキング

  has_many :blogs, dependent: :destroy
  has_many :blog_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # name を入力必須としているならば， user.name = "ゲスト" などが追加で必要
    end
  end

  def active_for_authentication?
    super && (is_valid == true)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :reject_user, only: [:create]

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to blogs_path # , notice: 'ゲストユーザーとしてログインしました。'
  end

  protected

  def reject_user
    @user = User.find_by(name: params[:user][:name].downcase)
    if @user
      if @user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false)
        flash[:error] = "退会済みです。"
        redirect_to root_path
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_q, only: [:index, :search]
  impressionist :actions => [:show]

  def index
    @users = @q.result.page(params[:page]).reverse_order
  end

  def show
    @user = User.find(params[:id])
    impressionist(@user) # トラッキング
    @users = User.all
    @blogs = @user.blogs.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(params_user)
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
  end

  def search
    @results = @q.result.page(params[:page]).reverse_order
  end

  def withdrawal
    @user = User.find(params[:id])
    @user.update(is_valid: false) # is_validカラムにフラグを立てる(defaultはtrue)
    reset_session # ログアウトさせる
    flash[:notice] = "退会完了致しました。"
    redirect_to root_path
  end

  private

  def set_q
    @q = User.ransack(params[:q])
  end

  def params_user
    params.require(:user).permit(:profile_image, :name, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class ="mt-5 ml-5">
  <h1 class ="mb-3">プロフィール編集</h1>

   <%= form_with model: @user,local:true do |f| %>
    <h4>プロフィール画像</h4>
   <%= f.attachment_field :profile_image %>
    <h4>名前</h4>
   <%=f.text_field :name %>
    <h4>紹介</h4>
   <%=f.text_area :introduction, size: "35x5"%><br>

   <%=f.submit "Update"%>
   <% end %>
</div>

app/views/users/index.html.erb
<main>
 <div class="containar-fluid">
  <div class="d-flex justify-content-between">
   <div class ="mt-5 ml-5">
　　<h1 class = "border-bottom border-dark fas fa-list"> 会員一覧</h1>
   </div>

   <div class ="mt-4 mr-5">
     <%= search_form_for @q, url: search_users_path do |f| %>
     <%#= f.label :name_cont, 'ユーザー名' %>
     <%= f.search_field :name_cont %>
     <%= f.submit '検索' %>
     <% end %>

     <h4 class="flex fas fa-search-plus mt-3">ユーザー一覧 並び替え</h4>
     <ul>
      <li class="list-inline-item"><%= sort_link(@q, :name, "名前") %></li>
     </ul>
    </div>
   </div>

  <div class="row mt-5 ml-5">
   <% @users.each do|user| %>
   <div class="col-auto">
    <p><%= link_to user_path(user) do %>
    <%=attachment_image_tag user, :profile_image, :fill, 180, 140, format: 'jpeg', fallback: "no_image.png", size:'180x140'  %>
    <% end %></p>

   <div class="row">
   <div class="col-12">
     <%=user.name %><br>
     <% if current_user.following?(user) %>
        <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
       <% else %>
        <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
       <% end %>
    </div>
   </div>

   </div>
   <% end %>
  </div>
  <%= paginate @users %>
 </div>
</main>

app/views/users/search.html.erb
<main>
 <h1 class="mt-5 ml-5 border-bottom border-dark fas fa-search-plus">検索結果</h1>
  <div class="row mt-3 ml-5">
   <% @results.each do |user| %>
    <div class="col-auto">
     <p><%= link_to user_path(user) do %>
        <%=attachment_image_tag user, :profile_image, :fill, 180, 140, format: 'jpeg', fallback: "no_image.png", size:'180x140' %>
        <% end %></p>

    <div class="row">
     <div class="col-12">
      <%=user.name %><br>
      <% if current_user.following?(user) %>
       <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
      <% else %>
       <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
      <% end %>
     </div>
    </div>

   <%#= link_to "削除", blog_path(blog), method: :delete%>
    </div>
   <% end %>
  </div>
<%= paginate @results %>
</main>

app/views/users/show.html.erb
<main>

 <div class="containar-fluid">
  <div class="row">
   <div class ="col-lg-5 mt-5 ml-5">
    <p4><%=attachment_image_tag @user, :profile_image, :fill, 480, 360, format: 'jpeg', fallback: "no_image.png", size:'480x360' %></p4>
     <h4 class ="mt-2">訪れたユーザー数(<%= @user.impressionist_count %>)</h4>
   </div>
   <div class ="col-lg-5 mt-5 ml-5">
    <h2 class = "fas fa-address-card"> <%=@user.name %></h2>
    <h4><%=@user.introduction %></h4>


    <h2><% unless @user == current_user %>
        <% if current_user.following?(@user) %>
         <%= link_to 'フォロー外す', unfollow_path(@user.id), method: :POST %>
        <% else %>
         <%= link_to 'フォローする', follow_path(@user.id), method: :POST %>
        <% end %>
        <% end %></h2>

    <h3>フォロー一覧 <%= @user.follower.count %>人</h3>
        <% @user.following_user.where.not(id: current_user.id).each do |user| %>
     <p>
      <%= link_to  user_path(user) do %>
      <%=attachment_image_tag user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.png", size:'30x30'  %>
      <% end %>
      <%=user.name %>
      <% if current_user.following?(user) %>
        <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
      <% else %>
        <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
      <% end %>
     </p>
        <% end %>

    <h3>フォロワー一覧　<%= @user.followed.count %>人</h3>
      <% @user.follower_user.where.not(id: current_user.id).each do |user| %>
     <p>
      <%= link_to user_path(user) do %>
      <%=attachment_image_tag user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.png", size:'30x30'  %>
      <% end %>
      <%=user.name %>
      <% if current_user.following?(user) %>
        <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
      <% else %>
        <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
      <% end %>
     </p>
      <% end %>


    <h4><% if current_user.name == User.find_by(name: "ゲスト").name %>
        <p>★ゲストログインの為、編集機能は使用できません</p>

        <% elsif @user == current_user %>
         <%= link_to "編集", edit_user_path(@user), class: "btn btn-outline-dark" %>
         <%= link_to "退会", users_withdrawal_path(current_user), method: :put, "data-confirm" => "本当に退会しますか？", class: "btn btn-outline-dark" %>
        <% end %>

        <% if current_user.id == User.find_by(id:1).id %>
         <%=link_to "ジャンル", genres_path, class: "btn btn-outline-dark" %>
        <% elsif current_user.id == User.find_by(id:6).id %> <!-- PF用adminログイン追加分 本来は重複の為、記述を削除予定 -->
         <%=link_to "ジャンル", genres_path, class: "btn btn-outline-dark" %>
        <% end %>
    </h4>

   </div>
  </div>

 <h2 class="mt-5 ml-5 border-bottom border-dark fas fa-list"> <%=@user.name %>様 投稿一覧</h2>
　<%= render "blogs/index" , blogs: @blogs %>

  </div>
</main>