config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    # get "sign_in", :to => "users/sessions#new"     #test用
    # get "sign_out", :to => "users/sessions#destroy"   #test用
  end

  root to: 'homes#top'
  get 'homes/about'

  resources :contacts, only: [:new, :create]

  resources :blogs do
    collection do
      get 'search'
      get "sort"
    end
    resources :blog_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
  end
  put "/users/:id/withdrawal" => "users#withdrawal", as: 'users_withdrawal' # 退会機能

  resources :genres, only: [:index, :create, :edit, :update, :destroy]

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  attachment :image # destroy: false
  attachment :profile_image, destroy: false

  belongs_to :genre

  belongs_to :user

  has_many:blog_comments, dependent: :destroy
  has_many:favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.ranking
    Blog.select('blogs.*', 'count(favorites.id) AS favorites').
      left_joins(:favorites).
      group('blogs.id').
      order('favorites DESC').
      limit(5)
  end
end

app/models/blog_comment.rb
class BlogComment < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :blogs, dependent: :destroy
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  attachment :image, destroy: false

  is_impressionable # トラッキング

  has_many :blogs, dependent: :destroy
  has_many :blog_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # name を入力必須としているならば， user.name = "ゲスト" などが追加で必要
    end
  end

  def active_for_authentication?
    super && (is_valid == true)
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_q, only: [:index, :search]

  def index
    @blogs = @q.result.page(params[:page]).reverse_order
    @blogs_new = Blog.all.order(created_at: "DESC").limit(5)
    @blogs_ranking = Blog.ranking
  end

  def new
    @blog = Blog.new
    @genres = Genre.all
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user = current_user
    @blog.save
    redirect_to blogs_path
  end

  def show
    @blogs = Blog.all
    @blog = Blog.find(params[:id])
    @blog_comment = BlogComment.new
  end

  def edit
    @blog = Blog.find(params[:id])
    @genres = Genre.all
  end

  def update
    @blog = Blog.find(params[:id])
    @blog.update(blog_params)
    redirect_to blog_path(@blog)
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end

  def search
    @results = @q.result.page(params[:page]).reverse_order
  end

  def sort # sort機能　params受け取り
    @params = params[:scene]
    @blogs = Blog.where(scene: @params)
  end

  private

  def blog_params
    params.require(:blog).permit(:image, :scene, :partner, :name, :price, :title, :body, :genre_id)
  end

  def set_q
    @q = Blog.ransack(params[:q])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @blogs_new = Blog.all.order(created_at: "DESC").limit(10)
    @blogs_ranking = Blog.select('blogs.*', 'count(favorites.id) AS favorites').
      left_joins(:favorites).
      group('blogs.id').
      order('favorites DESC').
      limit(5)
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_q, only: [:index, :search]
  impressionist :actions => [:show]

  def index
    @users = @q.result.page(params[:page]).reverse_order
  end

  def show
    @user = User.find(params[:id])
    impressionist(@user) # トラッキング
    @users = User.all
    @blogs = @user.blogs.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(params_user)
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
  end

  def search
    @results = @q.result.page(params[:page]).reverse_order
  end

  def withdrawal
    @user = User.find(params[:id])
    @user.update(is_valid: false) # is_validカラムにフラグを立てる(defaultはtrue)
    reset_session # ログアウトさせる
    flash[:notice] = "退会完了致しました。"
    redirect_to root_path
  end

  private

  def set_q
    @q = User.ransack(params[:q])
  end

  def params_user
    params.require(:user).permit(:profile_image, :name, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_comments_helper.rb
module BlogCommentsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>For you</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>

  </head>

  <body>
   <font face="Yu Gothic">
    <header>
     <nav class="navbar navbar-expand-lg navbar-dark bg-warning">
      <div class="container">
       <a class="navbar-brand" href="/"><span>For you <div class="fas fa-gift"></div></span></a>
        <ul class="navbar-nav ml-auto">
         <% if user_signed_in? %>
          <li><%= link_to "ホーム", root_path,class: 'fas fa-home nav-link text-light' %></li>
          <li><%= link_to "マイページ",user_path(current_user),class: 'fas fa-address-card nav-link text-light' %></li>
          <li><%= link_to "会員一覧",users_path,class: 'fas fa-users nav-link text-light' %></li>
          <li><%= link_to "投稿一覧",blogs_path ,class: 'fas fa-list nav-link text-light'%></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: 'fas fa-sign-out-alt nav-link text-light'%></li>
         <% else %>
          <li><%= link_to "ホーム",root_path,class: 'fas fa-home nav-link text-light' %></li>
          <li><%= link_to "For youとは", homes_about_path,class: 'fas fa-link nav-link text-light'%></li>
          <li><%= link_to "新規登録", new_user_registration_path,class: 'fas fa-user-plus nav-link text-light' %></li>
          <li><%= link_to "ログイン", new_user_session_path,class: 'fas fa-sign-in-alt nav-link text-light' %></li>
          <li><%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post,class: 'fas fa-sign-in-alt nav-link text-light' %></li>
         <% end %>
        </ul>
       </div>
      </div>
     </nav>
    </header>

    <%= yield %>

     <span id="top-btn">
      <a href="">
       <%= image_tag "top.png", width:"50",height:"50", data: {"turbolinks"=>false}, class: "top-btn" %>
      </a>
     </span>

    <footer>

     <div class='container mt-5'>
      <div class='row'>
       <div class='mx-auto'>
        <div class="mt-2 far fa-envelope"><%= link_to "お問い合わせ", new_contact_path %>
        </div>
        <p class ="mt-2">@for you.inc</p>
       </div>
      </div>
     </div>
    </footer>

   </font>
  </body>
</html>